# Generated by Django 3.2.16 on 2024-01-22 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerequest',
            name='underwriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_request', to=settings.AUTH_USER_MODEL, verbose_name='Андеррайтер'),
        ),
        migrations.AddField(
            model_name='scorereport',
            name='score_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_report', to='scoring.scorerequest', verbose_name='Запрос на скоринг'),
        ),
    ]
