# Generated by Django 3.2.16 on 2024-01-21 11:12
from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerequest',
            name='contract_date',
            field=models.DateTimeField(default=datetime.utcfromtimestamp(0), verbose_name='Дата контракта'),
            preserve_default=False,
        ),
    ]
