# Generated by Django 3.2.16 on 2024-01-21 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scorerequest_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorereport',
            name='contracts_completed',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Количество завершенных контрактов за 2 года'),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='experience',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='risk_level',
            field=models.CharField(choices=[('Умеренный', 'Умеренный'), ('Повышеный', 'Повышенный'), ('Высокий', 'Высокий')], max_length=12, verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='assets',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Активы'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='contract_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Сумма контракта'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='contract_current_outstanding',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Остаток денег по контракту'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='contract_total_outstanding',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Остаток денег по реестру контрактов'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='contracts_completed',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Количество завершенных контрактов за 2 года'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='current_assets',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Краткосрочные активы'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='current_liabilities',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Краткосрочные обязательства'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='experience',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='fixed_assets',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Основные средства'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='sales',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0001, message='Значение не может быть меньше 0.')], verbose_name='Доход от реализации'),
        ),
    ]
