# Generated by Django 3.2.16 on 2024-01-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorereport',
            name='license_category',
            field=models.SmallIntegerField(choices=[(0, 'Нет лицензии'), (1, 'Лицензия 1 категории'), (2, 'Лицензия 2 категории'), (3, 'Лицензия 3 категории')], default=0, verbose_name='Категория лицензии'),
        ),
    ]
