# Generated by Django 3.2.16 on 2024-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20240121_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorereport',
            name='risk_level',
            field=models.CharField(choices=[(0, 'Умеренный'), (1, 'Повышенный'), (2, 'Высокий')], max_length=12, verbose_name='Уровень риска'),
        ),
    ]
