# Generated by Django 3.2.16 on 2024-01-24 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_scorereport_license_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано/обновлено'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано/обновлено'),
        ),
    ]
