# Generated by Django 3.2.16 on 2024-01-21 06:56

import companies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bin',
            field=models.CharField(error_messages={'unique': 'Компания с таким БИН уже существует.'}, max_length=12, unique=True, validators=[companies.validators.validate_bin], verbose_name='БИН'),
        ),
    ]
